### ISSUE TITLE
PhysicTick

### ISSUE THREAD

**Issue by airidas-rom** [PrismarineJS/mineflayer-collectblock#130]
Mineflayer detected that you are using a deprecated event (physicTick)! Please use this event (physicsTick) instead.

Also when the bot is mining, and i give cooblestone to build up, it misses the build timing, not sure if its related to collectBlock, but above is the text im receiving when the bot is mining.

Also getting this:
Timeout: Took to long to decide path to goal!
    at error (C:\Users\roman\OneDrive\Desktop\mbot\node_modules\mineflayer-pathfinder\lib\goto.js:2:15)
    at EventEmitter.noPathListener (C:\Users\roman\OneDrive\Desktop\mbot\node_modules\mineflayer-pathfinder\lib\goto.js:28:17)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.monitorMovement (C:\Users\roman\OneDrive\Desktop\mbot\node_modules\mineflayer-pathfinder\index.js:446:11)
    at EventEmitter.emit (node:events:513:28)
    at tickPhysics (C:\Users\roman\OneDrive\Desktop\mbot\node_modules\mineflayer\lib\plugins\physics.js:81:11)
    at Timeout.doPhysics [as _onTimeout] (C:\Users\roman\OneDrive\Desktop\mbot\node_modules\mineflayer\lib\plugins\physics.js:70:7)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

**Comment by halil-alagl** [comment]
Ah, I've located where it's being used, and it doesn't seem to affect anything else. It appears to be more of a legacy issue, I reckon i am gonna send a pull req

**Comment by halil-alagl** [comment]
its seems like solved 
![code](https://github.com/PrismarineJS/mineflayer-collectblock/assets/139588876/0c6e1cdf-b86f-4612-82e7-7cf34aedd6c3)

**Comment by SilkePilon** [comment]
Yeah it was renamed but both events are completely the same
